### PR TITLE
[move-prover] Add support for multiple types in vectors

### LINKED ISSUE #653: [Prover] Not yet supported constant vector type: Vector(Primitive(Bool))
# 🐛 Bug

The Move Prover not yet supports constant bool vectors.

Happy to dig into it myself but tagging @rahxephon89 as he expressed interest in providing feedback.

## To reproduce

Run prover on the following module:
```
module bool_vec::bool_vec {
    fun foo(): vector<bool> {
        let v = vector[];
        v
    }
}
```

**Stack trace/error message**

```
thread 'main' panicked at 'not implemented: Not yet supported constant vector type: Vector(Primitive(Bool))', language/move-prover/bytecode/src/stackless_bytecode_generator.rs:1348:22
```

## Expected Behavior

This piece of code should verify correctly.

## System information

Main branch of the Move repo (sha: 3ac0cd7b78cc2a6d470b7fefbfd82b0c044ef576) built on a Mac.

### PR DESCRIPTION
**Pull request by rahxephon89**
## Motivation

Try to resolve #653 in a general way as suggested in #411. Since it is a little bit urgent, this PR is quite rough and a lot things are left unimplemented. Any comments and suggestions are welcomed. 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/move-language/move/blob/main/CONTRIBUTING.md#developer-workflow)?

Yes

## Test Plan

cargo test

### CODE REVIEW

File: language/move-prover/bytecode/src/stackless_bytecode_generator.rs [hunk 1]
```diff
@@ -1345,7 +1345,13 @@ impl<'a> StacklessBytecodeGenerator<'a> {
                         .collect::<Vec<BigUint>>();
                     Constant::AddressArray(b)
                 }
-                _ => unimplemented!("Not yet supported constant vector type: {:?}", ty),
+                _ => {
```
Comment (awelc) [inline language/move-prover/bytecode/src/stackless_bytecode_generator.rs:1348]: Do we want to keep `Type::Primitive(PrimitiveType::Address)` arm above or fold it into the more generic handling of constant vectors?

**Comment by awelc** [comment]
@rahxephon89 - thank you for getting to this so quickly!!!

File: language/move-prover/bytecode/src/stackless_bytecode_generator.rs (hunk 1 above)
Comment (rahxephon89) [reply language/move-prover/bytecode/src/stackless_bytecode_generator.rs:1348]: I would like to keep it for now in case my PR may break existing working code :)

File: language/move-model/src/ast.rs [hunk 2]
```diff
@@ -961,6 +961,7 @@ pub enum Value {
     Bool(bool),
     ByteArray(Vec<u8>),
     AddressArray(Vec<BigUint>),
```
Comment (meng-xu-cs) [inline language/move-model/src/ast.rs:963]: Maybe leave a TODO item here to indicate that the `AddressArray` may be merged into `Vector` in the future?

Comment (rahxephon89) [reply language/move-model/src/ast.rs]: done

File: language/move-prover/boogie-backend/src/boogie_helpers.rs [hunk 3]
```diff
@@ -329,6 +329,24 @@ pub fn boogie_address_blob(_options: &BoogieOptions, val: &[BigUint]) -> String
     }
 }
 
+pub fn boogie_constant_blob(_options: &BoogieOptions, val: &[Constant]) -> String {
+    let args = val.iter().map(|v| format!("{}", *v)).collect_vec();
```
Comment (meng-xu-cs) [inline language/move-prover/boogie-backend/src/boogie_helpers.rs:333]: This doesn't seem quite right to me.., I don't think any `Constant` can be `format!()` into boogie-recognizable text.

Perhaps a better solution is to have a helper function:
```rust
pub fn boogie_constant(options: &BoogieOptions, val: &Constant) -> String { .. }
```

And then call this `boogie_constant` inside the `.map()`

File: language/move-prover/boogie-backend/src/boogie_helpers.rs [hunk 4]
```diff
@@ -329,6 +329,48 @@ pub fn boogie_address_blob(_options: &BoogieOptions, val: &[BigUint]) -> String
...
+                .map(|v| boogie_constant(_options, v))
+                .collect_vec(),
+        ),
+        Constant::U16(num) => num.to_string(),
+        Constant::U32(num) => num.to_string(),
+    }
+}
+
+pub fn boogie_value_blob(_options: &BoogieOptions, val: &[Value]) -> String {
+    let args = val.iter().map(|v| format!("{}", *v)).collect_vec();
```
Comment (meng-xu-cs) [inline language/move-prover/boogie-backend/src/boogie_helpers.rs:366]: I think this `ast::Value` might also needs a helper function in boogie to replace the `format!("{}", *v)`

**Review by meng-xu-cs — COMMENTED** [review]
Just one more issue to address, all else look good to me.
