### PR TITLE
[move-prover] data invariants for map values

### LINKED ISSUE #680: [Prover] internal boogie error raised when using Table and struct invariant together
## Reproduce
Run Prover for the following example:
```
module 0x42::table_bug {
    use aptos_std::simple_map;

    struct R has key {
        map: simple_map::SimpleMap<address, S>
    }

    struct S has store {
        value: u64
    }
    spec S {
        invariant value >= 0;
    }

    fun f() acquires R {
        let _ = &borrow_global<R>(@0x42).map;
    }
}
```

Prover produces the following output:
```
$ move prove -t table_bug
[INFO] preparing module 0x42::table_bug
[INFO] transforming bytecode
[INFO] generating verification conditions
[INFO] 1 verification conditions
[INFO] running solver
Error: [internal] boogie exited with compilation errors:
output.bpl(1637,71): error: ";" expected
output.bpl(1637,92): error: ")" expected
2 parse errors detected in output.bpl
```

## Expected Output
Prover produces no internal error.

### PR DESCRIPTION
**Pull request by meng-xu-cs**
Added the encoding for data invariants via entrypoint assumptions and packref assertions:

```
t: Table<K, V>;

forall k: K :: $Contains(t, k) ==> (data-inv-predicate)($Get(t, k));
```

## Motivation

Close #680 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/move-language/move/blob/main/CONTRIBUTING.md#developer-workflow)?

Yes

## Test Plan

A new test case is added

### CODE REVIEW

File: language/move-model/src/exp_generator.rs [hunk 1]
```diff
@@ -208,6 +209,41 @@ pub trait ExpGenerator<'env> {
...
 
+    /// Creates a quantifier over the content of a map. The passed function `f` receives
+    /// an expression representing an element of the map and returns the quantifiers predicate;
+    /// if it returns None, this function will also return None, otherwise the quantifier will be
+    /// returned.
+    fn mk_map_quant_opt<F>(
+        &self,
+        kind: QuantKind,
+        map: Exp,
+        spec_fun_get: QualifiedId<SpecFunId>,
```
Comment (wrwg) [inline language/move-model/src/exp_generator.rs:220]: Document in the function comment what this is?

**Review by wrwg — APPROVED** [review]
Awesome.
