### PR TITLE
[move-prover] Fix the bug on handling recursive functions

### LINKED ISSUE #648: [Bug] Move Prover panicks during borrow analysis
# 🐛 Bug
The example Move project in [merge_sort.zip](https://github.com/move-language/move/files/9945968/merge_sort.zip) implements merge sort on `vector<u64>`. It compiles without issues (using move commit  3174338) and a simple test succeeds. The code does not contain any specifications apart from a `pragma opaque` which is required for a recursive function.
Still, the Move Prover panicks during model construction:
image

### PR DESCRIPTION
**Pull request by rahxephon89**
## Motivation

This PR tries to close #648 by avoiding panics in borrow_analysis and composition_analysis when handling recursive functions.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/move-language/move/blob/main/CONTRIBUTING.md#developer-workflow)?

Yes

## Test Plan

cargo test

### CODE REVIEW

File: language/move-prover/bytecode/src/compositional_analysis.rs [hunk 1]
```diff
@@ -38,11 +38,7 @@ impl<'a> SummaryCache<'a> {
                 if fun_env.is_native_or_intrinsic() {
                     None
                 } else {
-                    Some(
-                        fun_data.annotations.get::<Summary>().expect(
-                            "Failed to resolve summary; recursion or scheduler bug suspected",
-                        ),
-                    )
+                    fun_data.annotations.get::<Summary>()
```
Comment (sblackshear) [inline language/move-prover/bytecode/src/compositional_analysis.rs:41]: Would be good to add a TODO here--this will avoid the crash but (I believe) will still not allow us to create summaries for recursive or mutually recursive code.

File: language/move-prover/bytecode/src/function_target_pipeline.rs [hunk 2]
```diff
@@ -313,7 +313,18 @@ impl FunctionTargetPipeline {
         let mut dep_ordered = vec![];
         while !worklist.is_empty() {
             // Put functions with 0 calls first in line, at the end of the vector
-            worklist.sort_by(|(_, callees1), (_, callees2)| callees2.len().cmp(&callees1.len()));
+            worklist.sort_by(|(_, callees1), (caller2, callees2)| {
+                if Ordering::Equal == callees2.len().cmp(&callees1.len()) {
```
Comment (sblackshear) [inline language/move-prover/bytecode/src/function_target_pipeline.rs:317]: Comment here explaining  what this is doing might be useful

**Review by sblackshear — COMMENTED** [review]
Thanks for fixing this!

File: language/move-prover/bytecode/src/compositional_analysis.rs (hunk 1 above)
Comment (rahxephon89) [reply language/move-prover/bytecode/src/compositional_analysis.rs:43]: done

File: language/move-prover/bytecode/src/function_target_pipeline.rs (hunk 2 above)
Comment (rahxephon89) [reply language/move-prover/bytecode/src/function_target_pipeline.rs:319]: done

**Comment by meng-xu-cs** [comment]
More of a high-level question.

If issue #648 is about `panic` being an inappropriate behavior, we could change it into an error which exit gracefully instead of a hard panic. Personal I would prefer this approach.

As far as I know, there are several passes in the bytecode transformation pipeline that do not support recursion (borrow analysis being one for example). Each pass needs customized logic to run its analysis *in the presence of recursive calls*. Currently the way how borrow analysis handles recursive calls (i.e., by ignoring the callsite essentially) is not entirely correct in my understanding, so I would hesitate a bit in landing this part of the code.

**Comment by rahxephon89** [comment]
> More of a high-level question.
> 
> If issue #648 is about `panic` being an inappropriate behavior, we could change it into an error which exits gracefully instead of a hard panic. Personally I would prefer this approach.
> 
> As far as I know, there are several passes in the bytecode transformation pipeline that do not support recursion (borrow analysis being one for example). Each pass needs customized logic to run its analysis _in the presence of recursive calls_. Currently the way how borrow analysis handles recursive calls (i.e., by ignoring the callsite essentially) is not entirely correct in my understanding, so I would hesitate a bit in landing this part of the code.

Thanks for the advice. I have added to code to raise errors.

**Review by wrwg — APPROVED** [review]
Thanks for adding the error message. As a rule of thumb, any restrictions of the input to the prover should result in an error messages with source context. We should neither panic nor silently accept.
